name: CI
on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.0.x   # add this
          8.0.x   # keep if you also build/test any net8 projects- uses: actions/setup-dotnet@v4
    
    - name: Restore & Build & Test
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
        dotnet test  -c Release --no-build || true   

    - name: Publish (zip)
      run: |
        dotnet publish src/JiveApi/JiveApi.csproj -c Release -o publish
        cd publish && zip -r ../publish.zip . && cd ..

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop
        path: publish.zip
